---

name: "GitHub Action: Self-Test"

on:
  push:

env:
  PRODUCT_VERSION: "1.10.0"

jobs:
  setup-packer:
    name: Test `setup-packer`
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup `packer` (using local GitHub Action)
        uses: "./"
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Print `$PATH` for `packer`
        run: which packer

      - name: Print `packer` version
        run: packer version

      - name: Validate `packer` version is accurate
        run: "packer version | grep --silent 'Packer v${{ env.PRODUCT_VERSION }}'"

      - name: Run `packer fmt`
        run: packer fmt -check "./test/hello-world.pkr.hcl"

      - name: Setup `packer` with an invalid version (using local GitHub Action)
        uses: "./"
        id: invalid_version
        with:
          version: "invalid_version"
        continue-on-error: true

      - name: Validate invalid version failed
        if: steps.invalid_version.outcome == 'success'
        run: echo "Installing an invalid version expected to fail but did not" && exit 1

      - name: Setup `packer` with `latest` version (using local GitHub Action)
        uses: "./"
        id: latest_version

      - name: Print `packer` version
        run: packer version
