name: "GitHub Action: Self-Test"

on:
  push:

jobs:
  setup-packer:
    runs-on: ubuntu-latest
    name: Test `setup-packer`
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer` (using local GitHub Action)
        uses: "./"
        id: setup
        with:
          version: "1.5.0-beta.1"

      - name: Print `$PATH` for `packer`
        run: which packer

      - name: Print `packer` version
        run: packer version

      - name: Validate `packer` version is latest (`1.5.0-beta.1``)
        run: "if packer version | grep -q 'Nomad v1.5.0-beta.1'; then exit 0; else exit 1; fi;"

      - name: Run `packer fmt`
        run: packer fmt "${{ github.action_path }}./test/hello-world.pkr.hcl"

      - name: Setup `packer` with an invalid version (using local GitHub Action)
        uses: "./"
        id: invalid_version
        with:
          version: "invalid_version"
        continue-on-error: true

      - name: Validate invalid version failed
        if: steps.invalid_version.outcome == 'success'
        run: echo "Installing an invalid version expected to fail but did not" && exit 1

      - name: Setup `packer` with `latest` version (using local GitHub Action)
        uses: "./"
        id: latest_version

      - name: Print `packer` version
        run: packer version
